name: xeus-ocaml-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-dev 
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite >= 3.0,<4.0
  - xeus >=5.0.0,<6.0
  - xtl >=0.7,<0.8
